"""Stochastic processes that drive the environment.

These are intentionally simple, closed-form generators so the prototype is
fully reproducible and dependency-free. Swap them for real traces (solar
irradiance logs, request traces) when you move past the prototype stage.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass


def poisson(rng: random.Random, lam: float) -> int:
    """Draw a Poisson sample using Knuth's algorithm (no numpy needed)."""
    if lam <= 0:
        return 0
    L = math.exp(-lam)
    k = 0
    p = 1.0
    while True:
        k += 1
        p *= rng.random()
        if p <= L:
            return k - 1


@dataclass
class Task:
    """A unit of work generated by users."""
    cycles: float
    arrival_slot: int
    deadline_slot: int


class WorkloadProcess:
    """Stochastic task arrivals: Poisson count, exponential-ish sizes."""

    def __init__(self, rng: random.Random, arrival_rate: float,
                 cycles_mean: float, deadline_slots: int):
        self.rng = rng
        self.arrival_rate = arrival_rate
        self.cycles_mean = cycles_mean
        self.deadline_slots = deadline_slots

    def arrivals(self, slot: int) -> list[Task]:
        n = poisson(self.rng, self.arrival_rate)
        tasks = []
        for _ in range(n):
            # expovariate gives a light-tailed size; keep a small floor.
            cycles = max(0.1, self.rng.expovariate(1.0 / self.cycles_mean))
            tasks.append(Task(cycles=cycles,
                              arrival_slot=slot,
                              deadline_slot=slot + self.deadline_slots))
        return tasks


class RenewableProcess:
    """Diurnal solar harvest with multiplicative noise (passing clouds).

    Base curve is a clipped sinusoid peaking at solar noon; noise models the
    short-term uncertainty that makes the problem *stochastic*.
    """

    def __init__(self, rng: random.Random, slots_per_day: int,
                 peak: float, noise_std: float):
        self.rng = rng
        self.slots_per_day = slots_per_day
        self.peak = peak
        self.noise_std = noise_std

    def _base(self, slot: int) -> float:
        # phase so that ~slot 0 is midnight; daylight roughly half the day.
        phase = 2.0 * math.pi * ((slot % self.slots_per_day) / self.slots_per_day)
        val = math.sin(phase - math.pi / 2.0)  # -1 at midnight, +1 at noon
        return self.peak * max(0.0, val)

    def harvest(self, slot: int) -> float:
        base = self._base(slot)
        if base <= 0.0:
            return 0.0
        noise = self.rng.gauss(1.0, self.noise_std)
        return max(0.0, base * noise)
